//
//  AMADSize.h
//  SecondFramework
//
//  Created by appsynth on 6/16/15.
//  Copyright (c) 2015 Appsynth. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


/************************************
    Type
 *************************************/


typedef NS_ENUM(NSInteger, AMAdBannerSize) {
    // Standard Sizes
    AMAdSizeBanner,                     // Standard Banner
    AMAdSizeLargeBanner,                // Large Banner
    AMAdSizeMediumRectangleBanner,      // IAB Medium Rectangle
    AMAdSizeFullBanner,                 // IAB Full-Size Banner
    AMAdSizeLeaderboard,                // IAB Leaderboard
    AMAdSizeSmartBannerPortrait,        // Smart Banner
    AMAdSizeSmartBannerLandscape,       // Smart Banner
    
    // Non-standard Size
    AMAdSizeCustom,
    
    // Invalid Size
    AMAdSizeInvalid
};


@interface AMAdSize : NSObject
    
@property (nonatomic, assign) CGSize size;
@property (nonatomic, assign) AMAdBannerSize amAdBannerSize;    // enum value


#pragma mark - Custom Sizes


// Return a custom AMADSize for the provided CGSize
+ (AMAdSize *) AMAdSizeFromCGSize: (CGSize) aCGSize;


#pragma mark - Convenience Functions


// Returns a CGSize for the provided a AMAdSize
+ (CGSize) CGSizeFromAMAdSize: (AMAdSize *) aAMADSize;

// Return a CGSize for the provided a AMAdBannerSize constant, if the AMAdBannerSize is invalid or unknown, return CGSizeZero
+ (CGSize) CGSizeFromAMAdBannerSize: (AMAdBannerSize) aAMAdBannerSize;

// Returns YES if |size| is one of the predefined constants (AMAdBannerSize) or is a custom AMADAdSize generated by AMADSizeFromCGSize
+ (BOOL) isAMADAdSizeValid: (AMAdSize*) aSize;


#pragma mark - Utils


+ (BOOL) isStandardAMAdSize: (AMAdBannerSize) aBannerSize;


@end
